name: fuzzily
version: 0.1.0.0
synopsis: Filters a list based on a fuzzy string search
description: |
  Fuzzily is a library that filters a list based on a fuzzy string search.
  Uses 'TextualMonoid' to be able to run on different types of strings.
homepage: https://github.com/ad-si/Fuzzily
license: ISC
author: Adrian Sieber
maintainer: mail@adriansieber.com
copyright: Adrian Sieber
category: Text, Fuzzy, Search, Find, Filter

extra-source-files:
  - README.md

dependencies:
  - base
  - monoid-subclasses
  - protolude

default-extensions:
  - ImportQualifiedPost
  - NoImplicitPrelude

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -fno-warn-orphans

library:
  source-dirs: src

tests:
  fuzzily-test:
    main: tests.hs
    source-dirs: tests
    dependencies:
      - base
      - HUnit
      - fuzzily
