name: fuzzily
version: 0.2.0.0
synopsis: Filters a list based on a fuzzy string search
description: |
  Fuzzily is a library that filters a list based on a fuzzy string search.
  Uses 'TextualMonoid' to be able to run on different types of strings.
homepage: https://github.com/ad-si/Fuzzily
github: ad-si/Fuzzily
license: ISC
license-file: license.txt
author: Adrian Sieber
maintainer: mail@adriansieber.com
copyright: Adrian Sieber
category: Text, Fuzzy, Search, Find, Filter

extra-source-files:
  - README.md

default-extensions:
  - ImportQualifiedPost
  - NoImplicitPrelude

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -fno-warn-orphans

dependencies:
  - base >= 4.18.2 && < 5
  - protolude >= 0.3.4 && < 0.4

library:
  source-dirs: src
  dependencies:
    - monoid-subclasses >= 1.2.5 && < 1.3

tests:
  fuzzily-test:
    main: tests.hs
    source-dirs: tests
    dependencies:
      - HUnit >= 1.6 && < 1.7
      - fuzzily
